numero = str (input("Digite um valor: "))
print(type(numero))
#print ("O numero ", numero, "foi digitado")
#print ("O número {} foi digitado" .format(numero))
print (f"O número {numero} foi digitado")